spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          # Use your actual Okta domain, e.g., dev-123456.okta.com
          issuer-uri: https://dev-12757630.okta.com/oauth2/default
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/okta"
            scope:
              - openid
              - profile
              - email
          internal-client:
            provider: okta
            client-id: ${OKTA_INTERNAL_CLIENT_ID}
            client-secret: ${OKTA_INTERNAL_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - internal
        provider:
          okta:
            issuer-uri: https://dev-12757630.okta.com/oauth2/default

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG
