eureka:
 instance:
  prefer-ip-address: true
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

okta:
 oauth2:
  issuer: https://dev-bw4hsuafwgcqxetv.us.auth0.com/
  audience: https://dev-bw4hsuafwgcqxetv.us.auth0.com/api/v2/
